version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sergio
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: marketplacedb
    ports:
      - 5494:5432